version: '3.8'

services:
  sonelorefonte:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "12000:80"
    container_name: sonelorefonte
    volumes:
      - ./Sonelo:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - dbsonelorefonte
    environment:
      - MYSQL_HOST=dbsonelo
      - MYSQL_USER=sonelo
      - MYSQL_PASSWORD=1#2*DFjvcftifgkE456
      - MYSQL_DATABASE=sonelo
    restart: always

  dbsonelorefonte:
    image: mariadb:latest
    container_name: dbsonelorefonte
    environment:
      MYSQL_ROOT_PASSWORD: 5jcDr5.6?qE7S*
      MYSQL_DATABASE: sonelo
      MYSQL_USER: sonelo
      MYSQL_PASSWORD: 1#2*DFjvcftifgkE456
       
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "12001:3306"
    restart: always

  phpmyadminsonelorefonte:
    image: phpmyadmin:latest
    container_name: phpmyadminsonelorefonte
    environment:
      PMA_HOST: dbsonelo
      #PMA_USER: sonelo
      #PMA_PASSWORD: 1#2*DFjvcftifgkE456
    ports:
      - "12002:80"
    depends_on:
      - dbsonelorefonte
    restart: always

volumes:
  db_data:
